### ISSUE TITLE
اسم کلاس داخلی را لطفا تغییر بدید

### ISSUE THREAD

**Issue by miadzadfalah** [imanabidi/PersianDate.NET#1]
سلام
namespace را لطفا تغییر بدید
یک کامپوننت دیگر فارسی به این نام هست که موقع ادد کردن در آی دی ای پیغام خطا می دهد.
الان دقیق یادم نیست اما فکر کنم این بود
persiandate

با تشکر

**Comment by imanabidi** [comment]
thank you.

namespace changed to PersianDateHelper
